# Generated by Django 3.2.20 on 2023-10-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_date',
            new_name='product_date_hours',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_hours',
        ),
    ]
