# Generated by Django 3.2.20 on 2023-10-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
