# Generated by Django 3.2.20 on 2023-10-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20231029_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_date_hours',
        ),
    ]
