# Generated by Django 3.2.20 on 2023-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='time',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
