# Generated by Django 3.2.20 on 2023-09-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230927_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='elevenamtaken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='middaytaken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='onepmtaken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tenamtaken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='threepmtaken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twopmtaken',
        ),
    ]
